version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: stock-mariadb-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=stocks
    restart: unless-stopped
