version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: stock-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:latest
    container_name: stock-kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: stock-zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
  mariadb:
    image: mariadb:latest
    container_name: stock-mariadb-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=stocks
    restart: unless-stopped
  cassandra:
    image: cassandra:latest
    container_name: stock-cassandra-db
    ports:
      - "9042:9042"
    restart: unless-stopped
    volumes:
      - ./cfg/cassandra.yaml:/etc/cassandra/cassandra.yaml
  redis:
    image: redis:latest
    container_name: stock-redis-db
    ports:
      - "6379:6379"