version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: stock-mariadb-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=stocks
    restart: unless-stopped
  cassandra:
    image: cassandra:latest
    container_name: stock-cassandra-db
    ports:
      - 9042:9042
    restart: unless-stopped
    volumes:
      - ./cfgs/cassandra.yaml:/etc/cassandra/cassandra.yaml
